### ISSUE TITLE
twder should bypass SSL certification 

### ISSUE THREAD

**Issue by Conjuror** [jimms/twder#2]
Since bot.com.tw using their own certification, sometime it causes certification failed.

`Traceback (most recent call last):
  File "/Users/atsai/workspace/src/rokuro/src/rate_checker.py", line 27, in <module>
    current_rate = getRateByCurrentcy(currency)
  File "/Users/atsai/workspace/src/rokuro/src/rate_checker.py", line 9, in getRateByCurrentcy
    return twder.now(cur)
  File "/Users/atsai/.pyenv/versions/twstock/lib/python3.7/site-packages/twder/api.py", line 52, in now
    return now_all()[currency]
  File "/Users/atsai/.pyenv/versions/twstock/lib/python3.7/site-packages/twder/api.py", line 26, in now_all
    tree = __parse_tree(__CURRENT_QUOTE_URL)
  File "/Users/atsai/.pyenv/versions/twstock/lib/python3.7/site-packages/twder/api.py", line 15, in __parse_tree
    contents = request.urlopen(url).read()
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/atsai/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>`

**Comment by jimms** [comment]
@Conjuror 
Thank you for creating an issue. 🙏  However, I think `rate.bot.com.tw` is using the correct certificate (signed by Chunghwa telecom) so we should not bypass it.

![image](https://user-images.githubusercontent.com/322326/70874274-cf61dd00-1ff4-11ea-9ddc-bd3ae8ca188e.png)

I guess the problem is caused by the local certificate setting. This article may help you https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/

**Comment by RobertHWChiangSV** [comment]
Back to normal now. It's probably a temporary issue.

**Comment by jimms** [comment]
I think so because I also find this error log CI system. But retrying can fix the problem.

Thank you.
